### ISSUE TITLE
UA黑白名单功能会做吗

### ISSUE THREAD

**Issue by 8MiYile** [LiterMC/go-openbmclapi#10]
https://github.com/MCLF-CN/docs/issues/2

**Comment by zyxkad** [comment]
目前不清楚 UA 过滤是否有必要，因为请求签名是 @bangbang93 的BMCLAPI给的。我个人认为应是BMCLAPI做过滤而不是OpenBMCLAPI

**Comment by zyxkad** [comment]
UA 过滤另一个问题是如何同步列表

如果 BMCLAPI 明确表示不会限制 UA 我在做吧

**Comment by bangbang93** [comment]
要过滤也应该是bmclapi处理，不然我请求分过来了，来个黑名单怎么算

**Comment by 8MiYile** [comment]
@bangbang93 有道理 那就你那边处理了
