### ISSUE TITLE
第一部初始化的时候就读错参数的bug

### ISSUE THREAD

**Issue by 8MiYile** [LiterMC/go-openbmclapi#14]
![Screenshot_20240206_010844_com termux](https://github.com/LiterMC/go-openbmclapi/assets/25455400/9170617f-44ba-4f5c-9431-258a7b7528a2)
我看到这个方式的时候，我头都大了，我都不知道该怎么说他了，我甚至都说不清楚他到底是属于哪方面的问题

**Comment by 8MiYile** [comment]
我看了一下你读的参数值，都读错了

**Comment by zyxkad** [comment]
我大意了
