### ISSUE TITLE
Docker容器运行后不开放相应的端口

### ISSUE THREAD

**Issue by 9Bakabaka** [LiterMC/go-openbmclapi#16]
如题，我在使用docker镜像跑go-openbmclapi时遇到了端口不开放得问题，我设置public port是1299，而通过nmap扫描发现只开放了4000（仪表盘）的端口（已关闭防火墙并放行规则）
请问这种情况应怎么处理
![image](https://github.com/LiterMC/go-openbmclapi/assets/140469824/8297a6a8-f39c-4e6a-9305-a5460a71e0c0)
顺带附上我的配置文件

**Comment by zyxkad** [comment]
仪表盘的端口是与openbmclapi文件处理的端口一致的

**Comment by zyxkad** [comment]
啊对了, public_port不是docker开放的端口，它是你路由器开放的端口

**Comment by 9Bakabaka** [comment]
> 啊对了, public_port不是docker开放的端口，它是你路由器开放的端口

在路由器那边我已经开端口了
可是一直在报错提示"服务器查活失败，请检查端口是否可用(https://65c240a429a3ab75af1dc761.openbmclapi.933.moe:9198)：未能成功测量带宽: Timeout awaiting 'connect' for 5000ms"

**Comment by zyxkad** [comment]
额，配置里如果写了1299那么服务器是不应该访问9198的，你设置环境变量了么

**Comment by 9Bakabaka** [comment]
解决了，iptables问题，感谢回答
