### ISSUE TITLE
Dashboard支持分节点统计

### ISSUE THREAD

**Issue by RainC7** [LiterMC/go-openbmclapi#17]
Dashboard支持分节点统计
比如可以在dashboard中查看A节点多少流量请求数 B节点多少流量和请求数

**Comment by zyxkad** [comment]
所以为啥不找bangbang要俩号呢（

**Comment by 8MiYile** [comment]
你说的是 302模式-直接跳转 的统计吧

**Comment by RainC7** [comment]
准确的说应该是 统计List列表中不同节点的流量和请求数

**Comment by zyxkad** [comment]
如果只是统计，现在access.log里面加了一个`"extra": {"storage": "<XXXStorage xxx>"}`的记录，可以自己写一个脚本统计
