### ISSUE TITLE
经常突然断连并且无法恢复连接

### ISSUE THREAD

**Issue by djkcyl** [LiterMC/go-openbmclapi#24]
具体表现为程序跑着跑着突然不跑了，面板中显示已停止

**Comment by zyxkad** [comment]
应该是socket.io库的问题，应该已经修复了

**Comment by zyxkad** [comment]
貌似还没有解决

**Comment by djkcyl** [comment]
我写了个无限循环的脚本暂时能顶着（

**Comment by djkcyl** [comment]
感觉是高峰期的时候特别容易寄掉

**Comment by Dongyanmio** [comment]
> 应该，理论上，大概在v1.9.3-6修复了

貌似还是没有解决，依旧会显示“已停止”

**Comment by xiao-k233** [comment]
debug日志貌似还是不够详细，只看到Engine.IO RECV "3"之类的日志

**Comment by zyxkad** [comment]
呃呃，又修复了一个导致无法重连的问题，请尝试

<https://github.com/LiterMC/go-openbmclapi/releases/tag/v1.9.3-13>

**Comment by zyxkad** [comment]
应该可以关了
