### ISSUE TITLE
建议把write和read单独作为另外一个文件,limited_msg 换成读写锁

### ISSUE THREAD

**Issue by qiaoliangXgamemode** [LiterMC/go-openbmclapi#28]
sync.RWMutex 读写性能更高。
![image](https://github.com/LiterMC/go-openbmclapi/assets/46279874/e58671ac-126c-4d93-8023-32795eb889a6)

1. 我看你重新实现了Read Write Closer 操作，我更推荐你使用io.ReadWriteCloser
2. 心跳包建议设置成30s
3. write 无需每次for判断 writeAfter，直接按照tcp协议做法，ROT 延迟直接设置 RTT * 2
![image](https://github.com/LiterMC/go-openbmclapi/assets/46279874/d348cd01-969d-424a-bfdb-b580fd019e3f)

**Comment by zyxkad** [comment]
嗯，我不是很懂这一块，如果你感兴趣欢迎提交pr

**Comment by zyxkad** [comment]
不用RWMutex的原因是没有需要单独RLock的地方
