### ISSUE TITLE
在纯webdav模式下，全量的文件进行同步到云盘时会出现内存逐渐被耗尽

### ISSUE THREAD

**Issue by FOXBALL-ONE** [LiterMC/go-openbmclapi#39]
刚才跑了一下程序，内存占用一直在升高直到内存耗尽导致死机，但是磁盘占用以0.01g为单位做周期变化

**Comment by zyxkad** [comment]
执行指令`kill -s SIGQUIT`后程序会在运行目录输出一个dump-heap开头的文件，请发送该文件方便调试

**Comment by FOXBALL-ONE** [comment]
[dump-20240225-125745.txt](https://github.com/LiterMC/go-openbmclapi/files/14395277/dump-20240225-125745.txt)

**Comment by zyxkad** [comment]
啊，你这个版本太旧了，请升级成最新版本
