### ISSUE TITLE
面板出现429

### ISSUE THREAD

**Issue by kejinancheng** [LiterMC/go-openbmclapi#59]
面板状态码429 AxiosError: Request failed with status code 429
![image](https://github.com/LiterMC/go-openbmclapi/assets/108525877/1663e94c-39c7-4205-ae45-5b5572e607eb)

**Comment by kejinancheng** [comment]
挂上代理访问正常
![image](https://github.com/LiterMC/go-openbmclapi/assets/108525877/66121df7-c8ef-4d61-9afa-f4f98b5ade1d)

**Comment by zyxkad** [comment]
API有限速，防止爆破密码

登录后可以获得更高的API速率限制

也可以调整 config.yaml 里的 api-rate-limit
