### ISSUE TITLE
Error code 5

### ISSUE THREAD

**Issue by kejinancheng** [LiterMC/go-openbmclapi#60]
[WARN][01:04:22]: Engine.IO disconnected: Engine.IO: did not receive PING packet for a long time
[ERRO][01:04:22]: Socket.IO error: Engine.IO: did not receive PING packet for a long time
[INFO][01:04:24]: Engine.IO connected
[INFO][01:04:24]: Preparing to connect to center server (2/10)
[WARN][01:05:09]: Engine.IO disconnected: Engine.IO: did not receive PING packet for a long time
[ERRO][01:05:09]: Socket.IO error: Engine.IO: did not receive PING packet for a long time
[INFO][01:05:11]: Engine.IO connected
[INFO][01:05:11]: Preparing to connect to center server (3/10)
[WARN][01:05:56]: Engine.IO disconnected: Engine.IO: did not receive PING packet for a long time
[ERRO][01:05:56]: Socket.IO error: Engine.IO: did not receive PING packet for a long time
[INFO][01:05:58]: Engine.IO connected
[INFO][01:05:58]: Preparing to connect to center server (4/10)
[WARN][01:06:43]: Engine.IO disconnected: Engine.IO: did not receive PING packet for a long time
[ERRO][01:06:43]: Socket.IO error: Engine.IO: did not receive PING packet for a long time
[INFO][01:06:45]: Engine.IO connected
[INFO][01:06:45]: Preparing to connect to center server (5/10)
[WARN][01:07:30]: Engine.IO disconnected: Engine.IO: did not receive PING packet for a long time
[ERRO][01:07:30]: Socket.IO error: Engine.IO: did not receive PING packet for a long time
[INFO][01:07:32]: Engine.IO connected
[INFO][01:07:32]: Preparing to connect to center server (6/10)
[INFO][01:08:03]: Sending enable packet
[ERRO][01:08:03]: Cannot enable cluster: context deadline exceeded
[ERRO][01:08:03]: Program exiting with code 5
[ERRO][01:08:03]: Please read https://github.com/LiterMC/go-openbmclapi?tab=readme-ov-file#faq before report your issue
这是日志 之前是正常运行的 昨天跑着跑着突然跳这个

**Comment by zyxkad** [comment]
请检查网络环境

**Comment by kejinancheng** [comment]
网络环境完好 雨云的服务器

**Comment by zyxkad** [comment]
只要你的连接过GFW那么完好的环境是不可能的

**Comment by ghitori** [comment]
> 只要你的连接过GFW那么完好的环境是不可能的

我也遇到了这个问题
我现在使用的机器位于国内内网环境，使用GFW外的服务器作为内网穿透

这种情况下与主控链接会经过GFW外的穿透服务器么？为什么也会断连？
