### ISSUE TITLE
在已经运行了一个go-openbmclapi的alist上再运行一个会导致崩溃

### ISSUE THREAD

**Issue by xuzhichang** [LiterMC/go-openbmclapi#66]
[20240525-20.log](https://github.com/LiterMC/go-openbmclapi/files/15443450/20240525-20.log)

**Comment by zyxkad** [comment]
bmclapi主控不支持在同一个CLUSER_ID上同时运行多个openbmclapi。不是alist也不是go-openbmclapi的问题

**Comment by xuzhichang** [comment]
但是我使用的是多个CLUSER_ID

**Comment by xuzhichang** [comment]
额，我我似乎配置文件写错了，对不起打扰了（
