### ISSUE TITLE
各存储流量统计在重新启动时出现错误

### ISSUE THREAD

**Issue by Dongyanmio** [LiterMC/go-openbmclapi#69]
![6d653d06ef4ff096bc3b17516ff942c4](https://github.com/LiterMC/go-openbmclapi/assets/63110083/0b2a6d17-8ec9-437d-8ef7-83e3d9469913)
![92792b407daef8fd507565cd55a617b3](https://github.com/LiterMC/go-openbmclapi/assets/63110083/f13d6692-8fe9-4013-b014-de24a91e8424)
![849a1c4a88418778e1064d599c160133](https://github.com/LiterMC/go-openbmclapi/assets/63110083/52ddfc51-bdbd-4135-ba1a-83e895177e05)
众所周知，189的流量+139的流量=189的流量=139的流量=全部的流量

**Comment by zyxkad** [comment]
可还行，给个链接我看一下

**Comment by Dongyanmio** [comment]
https://bmclapi.zeroctagon.top:52093/dashboard/

**Comment by zyxkad** [comment]
> https://bmclapi.zeroctagon.top:52093/dashboard/


<img width="844" alt="Screenshot 2024-05-26 at 09 41 43" src="https://github.com/LiterMC/go-openbmclapi/assets/91082411/7f7fb6d0-a0de-4b9d-b2b0-09d837e582b7">

**Comment by Dongyanmio** [comment]
> > https://bmclapi.zeroctagon.top:52093/dashboard/
> 
> <img alt="Screenshot 2024-05-26 at 09 41 43" width="844" src="https://private-user-images.githubusercontent.com/91082411/333892005-7f7fb6d0-a0de-4b9d-b2b0-09d837e582b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mzg0MjIsIm5iZiI6MTcxNjczODEyMiwicGF0aCI6Ii85MTA4MjQxMS8zMzM4OTIwMDUtN2Y3ZmI2ZDAtYTBkZS00YjlkLWIyYjAtMDlkODM3ZTU4MmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE1NDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZDZjYWI2YjUxM2IzYzhkMDc3ZTYzNWM2YTY2NWEyNTMxYjVjZWY0NjRkNjkyMTg0YjE3MDUxZGJiNWE1YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Viq3uODsHOE4kZEUJchqokr5sbuvg6eBnEFAE77Ydn4">

笑死，忘了，这服务器禁境外好像

**Comment by Dongyanmio** [comment]
奇怪，好像八蓝米的就没这个问题
https://bmclapi.8mi.tech/dashboard/

**Comment by Dongyanmio** [comment]
估计是域名这边的问题，麻烦用下IP试试看（记得关重定向）
http://103.40.13.88:52093/dashboard/

**Comment by zyxkad** [comment]
IP访问超时

**Comment by Dongyanmio** [comment]
> IP访问超时

你在哪啊？

**Comment by zyxkad** [comment]
加拿大🇨🇦

**Comment by Dongyanmio** [comment]
> 加拿大🇨🇦

加拿大不通也正常，毕竟服务器远处中国江苏嘛
试试看用croxy.network这个网页访问看看

**Comment by zyxkad** [comment]
对了，加载其他存储的时候如果网络不好是需要一段时间的，你看一下控制台连接有没有走完

**Comment by Dongyanmio** [comment]
没事了，是那一天存储的网络的问题，现在好了（学校里网络比家里网络好？不敢相信）麻烦关一下谢谢（在学校关不了）
________________________________
发件人: Kevin Z ***@***.***>
发送时间: 2024年5月29日 10:09
收件人: LiterMC/go-openbmclapi ***@***.***>
抄送: 冬烟mio ***@***.***>; Author ***@***.***>
主题: Re: [LiterMC/go-openbmclapi] 各存储流量统计出现错误 (Issue #69)


对了，加载其他存储的时候如果网络不好是需要一段时间的，你看一下控制台连接有没有走完

―

**Comment by Dongyanmio** [comment]
还是有问题，我现在是两个网盘（一个139，一个189）
正常应该是 139Cloud+189Cloud=Overall 对吧
但是现在我是在有的时间段是139Cloud=189Cloud=Overall
有的时间又是正常的（这里就很奇怪了）

解析问题应该是cloudflare那边的问题，回去我试试换个DNS解析商
IP超时我是真没法解决，纯属网络问题（）
________________________________
发件人: 谢 谨鸿 ***@***.***>
发送时间: 2024年5月29日 17:36
收件人: LiterMC/go-openbmclapi ***@***.***>
主题: 回复: [LiterMC/go-openbmclapi] 各存储流量统计出现错误 (Issue #69)

没事了，是那一天存储的网络的问题，现在好了（学校里网络比家里网络好？不敢相信）麻烦关一下谢谢（在学校关不了）
________________________________
发件人: Kevin Z ***@***.***>
发送时间: 2024年5月29日 10:09
收件人: LiterMC/go-openbmclapi ***@***.***>
抄送: 冬烟mio ***@***.***>; Author ***@***.***>
主题: Re: [LiterMC/go-openbmclapi] 各存储流量统计出现错误 (Issue #69)


对了，加载其他存储的时候如果网络不好是需要一段时间的，你看一下控制台连接有没有走完

―
