### ISSUE TITLE
wss不能保持连接

### ISSUE THREAD

**Issue by 8MiYile** [LiterMC/go-openbmclapi#7]
![image](https://github.com/LiterMC/go-openbmclapi/assets/25455400/3a236254-07fb-4c72-8c69-2ad669f11d0a)
掉线图

**Comment by zyxkad** [comment]
这代表bmclapi服务端有很长一段时间没有发送任何数据包

**Comment by 8MiYile** [comment]
懂了 马上问问93在干嘛
