### ISSUE TITLE
因先行关闭打洞导致禁用失败

### ISSUE THREAD

**Issue by kndxhz** [LiterMC/go-openbmclapi#74]
![image](https://github.com/user-attachments/assets/f948aad6-f4d6-4a8e-b268-98c42d23fac3)
（请忽略颜色渲染错误）
一句话就能解释：由于打洞隧道先行关闭，导致禁用失败掉trust

**Comment by zyxkad** [comment]
冷知识，关闭是同时进行的

禁用的时候还会有连接传入吗，我记得主控之前没有这个逻辑吧
