### ISSUE TITLE
希望添加对Android支持

### ISSUE THREAD

**Issue by Whirity404** [LiterMC/go-openbmclapi#76]
go设备列表有Android，希望添加对Android支持以可以在Termux上运行
![Screenshot_20240812_185434](https://github.com/user-attachments/assets/79b46a89-2e5d-4056-b80b-37365543ca2c)
![Screenshot_20240812_185427](https://github.com/user-attachments/assets/99cc8444-cde2-4eaf-b4f2-f65bccdb694a)

**Comment by WorldHim** [comment]
#38？
